#!/usr/bin/env python

####
# Copyright (C) 2012, 2020 Angelo Cano
#
# This file is part of Qvmdis.
#
# Qvmdis is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Qvmdis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Qvmdis.  If not, see <https://www.gnu.org/licenses/>.
####

import AddParentSysPath

from pylint import epylint
import glob, sys

files = [ "../qvmdis" ]
files.extend(glob.glob("../*.py"))
files.extend(["check-pylint", "opinfo", "qvmjoin", "qvmsplit"])
files.extend(glob.glob("*.py"))

for f in files:
    print("pylint check of %s" % f)

    #epylint.lint(options=["--errors-only"], filename=f)

    (pylint_stdout, pylint_stderr) = epylint.py_run("\"%s\" --errors-only" % f, return_std=True)
    sys.stdout.write(pylint_stdout.getvalue())

print("done.")
