#!/usr/bin/env python

# Copyright (C) 2012, 2020 Angelo Cano
#
# This file is part of Qvmdis.
#
# Qvmdis is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Qvmdis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Qvmdis.  If not, see <https://www.gnu.org/licenses/>.

# allow importing from parent directory
# https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder
#  answered Jun 22 '12 at 14:30  Remi
import inspect, os, sys
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

from QvmFile import QvmFile

QVM_MAGIC = 0x12721444

def usage ():
    sys.stderr.write("%s <qvm file>\n" % sys.argv[0])
    sys.exit (1)

def main ():
    if len(sys.argv) < 2:
        usage ()

    qvm = QvmFile(sys.argv[1])
    qvm.print_header ()

    f = open("header-info.txt", "w")
    f.write ("instruction count: %d\n" % qvm.instructionCount)
    f.write ("bss segment length: %d\n" % qvm.bssSegLength)
    f.close()

    fcodew = open("x.code", "wb")
    # unpadded code
    fcodew.write(qvm.get_code())
    fcodew.close()

    fcode = open("xpadded.code", "wb")
    fcode.write(qvm.codeData[:qvm.codeSegLength])
    fcode.close()

    fdata = open("x.data", "wb")
    fdata.write (qvm.dataData[:qvm.dataSegLength])
    fdata.close()

    flit = open("x.lit", "wb")
    flit.write (qvm.litData[:qvm.litSegLength])
    flit.close()

    qvm.close()

if __name__ == "__main__":
    main ()
